# Generated by Django 3.2 on 2021-06-27 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_costumer_photo'),
        ('dashboard', '0005_alter_produit_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.costumer'),
        ),
    ]
