# Generated by Django 3.2 on 2021-06-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_commande_utilisateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='utilisateur',
            new_name='Costumer',
        ),
    ]
