# Generated by Django 3.2 on 2021-06-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_utilisateur_commande_costumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='address',
            field=models.CharField(default=' ', max_length=250),
        ),
        migrations.AddField(
            model_name='commande',
            name='city',
            field=models.CharField(default='Maroc', max_length=100),
        ),
        migrations.AddField(
            model_name='commande',
            name='postal_code',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
