# Generated by Django 3.2 on 2021-07-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210628_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='Costumer',
            new_name='costumer',
        ),
        migrations.AlterField(
            model_name='commande',
            name='city',
            field=models.CharField(default='Casablanca', max_length=100),
        ),
        migrations.AlterField(
            model_name='commande',
            name='prixTotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
