# Generated by Django 3.2 on 2021-07-04 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210704_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='costumer',
            new_name='Costumer',
        ),
    ]
