# Generated by Django 3.2 on 2021-06-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/costumers/'),
        ),
    ]
